enabled tests

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -3,19 +3,39 @@
 #
 export ZOPEN_TYPE="TARBALL"
 export ZOPEN_TARBALL_URL="https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.1.tar.gz"
-export ZOPEN_TARBALL_DEPS="curl gzip make coreutils"
+export ZOPEN_TARBALL_DEPS="curl gzip make coreutils zoslib"
 
 export ZOPEN_EXTRA_CFLAGS='-qnocsect'
 export ZOPEN_BOOTSTRAP=skip
 export ZOPEN_CONFIGURE=skip
 export ZOPEN_INSTALL_OPTS="install POSIX_ENV=Yes prefix=\${ZOPEN_INSTALL_DIR}" 
 export ZOPEN_NAME="xxHash-0.8.1"
-export ZOPEN_CHECK="skip"
+#export ZOPEN_CHECK="skip"
 rm -f v0.8.1
 ln -s ${ZOPEN_NAME} v0.8.1
 
 zopen_check_results()
 {
-  return 3 # non-functional
+  FAILURE=0 
+  chk="$1/$2_check.log"
+  totalTests=$(egrep "\.\/xxhsum" $chk | wc -l)
+  egrep "a9c413a5c9548a52  stdin" $chk ; [ $? -ne 0 ] && (( $FAILURE=$FAILURE+1 )) 
+  egrep "a9c413a5c9548a52  xxhash.c" $chk ; [ $? -ne 0 ] && (( $FAILURE=$FAILURE+1 )) 
+  egrep "0b9f9eb1  xxhash.c" $chk ; [ $? -ne 0 ] && (( $FAILURE=$FAILURE+1 )) 
+  egrep "75323380c1b81bbbe6b4fc5c377a18ff  xxhash.c" $chk ; [ $? -ne 0 ] && (( $FAILURE=$FAILURE+1 )) 
+  egrep "11\#XXH128" $chk ; [ $? -ne 0 ] && (( $FAILURE=$FAILURE+1 )) 
+  egrep "2\#XXH32 unaligned" $chk ; [ $? -ne 0 ] && (( $FAILURE=$FAILURE+1 )) 
+  egrep "5\#XXH3_64b" $chk ; [ $? -ne 0 ] && (( $FAILURE=$FAILURE+1 )) 
+  egrep "1-XXH3_64b w\/seed unaligned" $chk ; [ $? -ne 0 ] && (( $FAILURE=$FAILURE+1 )) 
+  egrep "e6b4fc5c377a18ff" $chk ; [ $? -ne 0 ] && (( $FAILURE=$FAILURE+1 )) 
+  egrep "Wrong parameters" $chk ; [ $? -ne 0 ] && (( $FAILURE=$FAILURE+1 )) 
+  passedTests=$(expr $totalTests - $FAILURE) 
+
+# Echo the following information to guage build health
+cat <<TEST
+actualFailures:$FAILURE
+totalTests:$totalTests
+expectedFailures:0
+TEST
 }
 
